# Generated by Django 5.2.1 on 2025-06-09 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reservations.reservation",
            ),
        ),
        migrations.AlterField(
            model_name="diary",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
