# Generated by Django 5.2.1 on 2025-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("category", models.CharField(max_length=50)),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
