# Generated by Django 5.2.1 on 2025-06-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
